# fly.toml app configuration file generated for alloydflanagan-htmx on 2025-06-03T14:22:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alloydflanagan-htmx'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.24.3'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "settings_db"
  destination = "/app/data"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
